language: rust
rust:
  - nightly

cache: cargo

script:
  - cargo check --all --verbose
  - cargo test --all --verbose

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo "cargo-tarpaulin already installed."
  fi

after_success:
  # Codecov
  - |
    if [[ "$TRAVIS_RUST_VERSION" ==  "nightly" ]]; then
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
    fi
