[package]
name = "lusion"
version = "0.0.0"
authors = ["Yanhai <shimmly@live.cn>"]
edition = "2018"
readme = "README.md"
license = "MIT or Apache-2.0"

[dependencies]
http = "0.1"
tide = "0.1"
futures-preview = "=0.3.0-alpha.14"
